import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  style: ["normal", "italic"],
});


export const metadata: Metadata = {
  title: "yee ern",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased min-h-screen bg-background`}
      >
        <main className="max-w-2xl px-6 pt-8 pb-12 md:pt-12 md:pb-20">
        {children}
        </main>
      </body>
    </html>
  );
}
